name: CI

on:
  pull_request:
    branches:
      - release
      - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ./batbot_tendon_controller
        run: pio run -e adafruit_grandcentral_m4

  native-test:
    name: native-unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Test PlatformIO Project
        working-directory: ./batbot_tendon_controller
        run: pio test -e native_testing

  hil-test:
    name: hil-unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Test PlatformIO Project
        working-directory: ./batbot_tendon_controller
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.TEST_SERVER_PAT }}
        run: pio remote --agent raspberrypi test -e embedded_testing --upload-port /dev/ttyACM0 --test-port /dev/ttyACM0