name: Docs

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Sphinx & Dependencies
        run: |
          cd batbot_bringup
          pip install -r requirements.txt
          python3 setup.py build
          pip install .
          cd ../doc
          make html

      - name: Override Jekyll
        run: sudo touch doc/build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: doc/build/html
          branch: gh-pages
          token: ${{ secrets.GHPAGES_TOKEN }}
